return {
  "catppuccin/nvim",
  name = "catppuccin",
  lazy = false,
  priority = 100,
  config = function()
    require("catppuccin").setup({
      background = {
        light = "latte",
        dark = "mocha",
      },
      color_overrides = {
        latte = {
          rosewater = "#c14a4a",
          flamingo = "#c14a4a",
          pink = "#945e80",
          mauve = "#945e80",
          red = "#c14a4a",
          maroon = "#c14a4a",
          peach = "#c35e0a",
          yellow = "#a96b2c",
          green = "#6c782e",
          teal = "#4c7a5d",
          sky = "#4c7a5d",
          sapphire = "#4c7a5d",
          blue = "#45707a",
          lavender = "#45707a",
          text = "#654735",
          subtext1 = "#7b5d44",
          subtext0 = "#8f6f56",
          overlay2 = "#a28368",
          overlay1 = "#b6977a",
          overlay0 = "#c9aa8c",
          surface2 = "#A79C86",
          surface1 = "#C9C19F",
          surface0 = "#DFD6B1",
          base = "#fbf1c7",
          mantle = "#F3EAC1",
          crust = "#E7DEB7",
        },
        mocha = {
          rosewater = "#ff8389",
          flamingo = "#ff8389",
          red = "#ff8389",
          maroon = "#ff8389",
          pink = "#ff7eb6",
          mauve = "#be95ff",
          peach = "#d44a1c",
          yellow = "#ab8600",
          green = "#08bdba",
          teal = "#33b1ff",
          sky = "#33b1ff",
          sapphire = "#33b1ff",
          blue = "#78a9ff",
          lavender = "#78a9ff",
          text = "#ffffff",
          subtext1 = "#f4f4f4",
          subtext0 = "#e0e0e0",
          overlay2 = "#adadad",
          overlay1 = "#949494",
          overlay0 = "#7a7a7a",
          surface2 = "#4f4f4f",
          surface1 = "#383838",
          surface0 = "#2e2e2e",
          base = "#161616",
          mantle = "#0d0d0d",
          crust = "#000000",
        },
      },
      styles = {
        comments = { "italic" },
        conditionals = { "italic" },
        functions = { "italic" },
        keywords = { "italic" },
        numbers = { "bold" },
        types = { "bold" },
      },
      integrations = {
        lsp_trouble = true,
        dashboard = false,
        hop = true,
        nvimtree = false,
        native_lsp = {
          enabled = true,
          virtual_text = {
            errors = { "italic" },
            hints = { "italic" },
            warnings = { "italic" },
            information = { "italic" },
          },
          underlines = {
            errors = { "undercurl" },
            hints = { "undercurl" },
            warnings = { "undercurl" },
            information = { "undercurl" },
          },
        },
      },
      highlight_overrides = {
        all = function(colors)
          return {
            NormalFloat = { bg = colors.mantle },
            FloatBorder = { bg = colors.mantle, fg = colors.mantle },
            CursorLineNr = { fg = colors.mauve, style = { "bold" } },
            PmenuSel = { bg = colors.surface0, fg = "" },
            Pmenu = { bg = colors.mantle },
            PmenuSbar = { bg = colors.crust },
            PmenuThumb = { bg = colors.surface0 },
            VertSplit = { fg = colors.base },
            CmpGhostText = { link = "Comment" },
            Folded = { link = "Comment" },
            LazyBackdrop = { bg = colors.base },

            TelescopeSelection = { bg = colors.surface0 },
            TelescopePromptCounter = { fg = colors.mauve, style = { "bold" } },

            TelescopePromptPrefix = { bg = colors.surface0 },
            TelescopePromptNormal = { bg = colors.surface0 },
            TelescopeResultsNormal = { bg = colors.mantle },
            TelescopePreviewNormal = { bg = colors.crust },

            TelescopePromptBorder = { bg = colors.surface0, fg = colors.surface0 },
            TelescopeResultsBorder = { bg = colors.mantle, fg = colors.mantle },
            TelescopePreviewBorder = { bg = colors.crust, fg = colors.crust },
            TelescopePreviewMessage = { fg = colors.teal, style = { "italic" } },

            TelescopePromptTitle = { fg = colors.surface0, bg = colors.surface0 },
            TelescopeResultsTitle = { fg = colors.mantle, bg = colors.mantle },
            TelescopePreviewTitle = { fg = colors.crust, bg = colors.crust },

            GitSignsChange = { fg = colors.peach },
            GitSignsCurrentLineBlame = { link = "Comment" },

            HimalayaHead = { fg = colors.overlay0 },

            IndentBlanklineChar = { fg = colors.surface0 },
            IndentBlanklineContextChar = { fg = colors.surface2 },

            NoiceConfirm = { bg = colors.mantle, fg = colors.mauve },
            NoiceCmdlineIconLua = { fg = colors.blue },
            NoiceConfirmBorder = { bg = colors.mantle, fg = colors.mantle },
            NoiceMini = { link = "Comment" },
            NoiceLspProgressClient = { fg = colors.blue, style = { "italic", "bold" } },
            NoiceCmdlinePopup = { bg = colors.mantle },
            NoiceCmdlinePopupBorder = { bg = colors.mantle, fg = colors.mantle },
            NoiceCmdlinePopupBorderSearch = { bg = colors.mantle, fg = colors.mantle },

            Todo = { fg = colors.mauve, bg = colors.none, style = { "bold" } },
            ["@comment.error"] = { fg = colors.red, bg = colors.none, style = { "bold" } },
            ["@comment.warning"] = { fg = colors.yellow, bg = colors.none, style = { "bold" } },
            ["@comment.note"] = { fg = colors.blue, bg = colors.none, style = { "bold" } },
            ["@comment.todo"] = { fg = colors.mauve, bg = colors.none, style = { "bold" } },

            Structure = { fg = colors.pink },
            StorageClass = { fg = colors.pink },
            Type = { fg = colors.pink, style = { "bold" } },
            Constant = { fg = colors.text, style = { "bold" } },
            Number = { fg = colors.text },
            Float = { fg = colors.text },
            Boolean = { fg = colors.pink },
            ["@function.builtin"] = { fg = colors.pink },
            ["@method"] = { fg = colors.pink },
            ["@constant"] = { fg = colors.text, style = { "bold" } },
            ["@variable.builtin"] = { fg = colors.pink },
            ["@type.builtin"] = { fg = colors.pink, style = { "bold" } },
            ["@tag.attribute.tsx"] = { fg = colors.mauve, style = { "italic" } },
            ["@tag.attribute"] = { fg = colors.mauve, style = { "italic" } },
            ["@tag.builtin.tsx"] = { fg = colors.mauve },
          }
        end,
      },
    })

    vim.api.nvim_command("colorscheme catppuccin")
  end,
}
