local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable",
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
  { import = "uwu.plugins.pairs" },
  { import = "uwu.plugins.theme" },
  { import = "uwu.plugins.blink" },
  { import = "uwu.plugins.colorizer" },
  { import = "uwu.plugins.comment" },
  { import = "uwu.plugins.icons" },
  { import = "uwu.plugins.gitsigns" },
  { import = "uwu.plugins.heirline" },
  { import = "uwu.plugins.direnv" },
  { import = "uwu.plugins.noice" },
  { import = "uwu.plugins.surround" },
  { import = "uwu.plugins.telescope" },
  { import = "uwu.plugins.treesitter" },
  { import = "uwu.plugins.which-key" },
  { import = "uwu.plugins.hop" },
  { import = "uwu.plugins.conform" },
  { import = "uwu.plugins.himalaya" },
  { import = "uwu.plugins.crates" },
  { import = "uwu.plugins.minty" },
  { import = "uwu.plugins.neogit" },
  { import = "uwu.plugins.highlight-undo" },
  { import = "uwu.plugins.term-edit" },
}, {
  defaults = {
    lazy = true,
    version = false,
  },
  change_detection = {
    enabled = false,
    notify = false,
  },
  ui = {
    icons = {
      cmd = " ",
      config = "",
      event = "",
      ft = " ",
      init = "",
      import = "",
      keys = "",
      lazy = " ",
      loaded = "",
      not_loaded = "",
      plugin = "󱧕",
      runtime = "",
      source = " ",
      start = "",
      task = "",
      list = {
        "",
        "",
        "",
        "‒",
      },
    },
  },
  install = {
    colorscheme = { "catppuccin", "habamax" },
  },
  performance = {
    cache = {
      enabled = true,
    },
    rtp = {
      reset = true,
      disabled_plugins = {
        "2html_plugin",
        "tohtml",
        "getscript",
        "getscriptPlugin",
        "gzip",
        "logipat",
        "netrw",
        "netrwPlugin",
        "netrwSettings",
        "netrwFileHandlers",
        "matchit",
        "tar",
        "tarPlugin",
        "rrhelper",
        "spellfile_plugin",
        "vimball",
        "vimballPlugin",
        "zip",
        "zipPlugin",
        "tutor",
        "rplugin",
        "syntax",
        "synmenu",
        "optwin",
        "compiler",
        "bugreport",
        "ftplugin",
      },
    },
  },
})
